name: Artifacts
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 12
          platform: x64
      - run: |
          ./build -j$(nproc) x86_64-windows-gnu baseline
          ./package
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: zig+llvm+lld+clang-x86_64-windows-gnu-0.9.0-dev.1249+210ef5af8
          path: out/windows-devkit
          if-no-files-found: error
